// <auto-generated />
using System;
using JotFormAuthenticator.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JotFormAuthenticator.Migrations
{
    [DbContext(typeof(FormDBContext))]
    [Migration("20190501095946_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JotFormAuthenticator.Models.FieldModel", b =>
                {
                    b.Property<int>("FieldModelID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("DeletedBy");

                    b.Property<int>("FieldID");

                    b.Property<string>("FieldName")
                        .IsRequired();

                    b.Property<string>("FieldParentName");

                    b.Property<string>("FieldValue")
                        .IsRequired();

                    b.Property<int>("FormModelID");

                    b.Property<long>("SubmissionID");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("FieldModelID");

                    b.HasIndex("FormModelID");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("JotFormAuthenticator.Models.FormModel", b =>
                {
                    b.Property<int>("FormModelID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Accepted");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("DeletedBy");

                    b.Property<long>("FormID");

                    b.Property<string>("FormName")
                        .IsRequired();

                    b.Property<long>("SubmissionID");

                    b.Property<string>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("FormModelID");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("JotFormAuthenticator.Models.FieldModel", b =>
                {
                    b.HasOne("JotFormAuthenticator.Models.FormModel", "Form")
                        .WithMany("FormFields")
                        .HasForeignKey("FormModelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
